#! /usr/bin/env sh
ROOT="$PWD"
VENDOR="$ROOT/vendor"
ADDONS="$VENDOR/addons"

MODULE_TITLE='Nginx: Access Key'
MODULE_NAME='nginx-accesskey'
MODULE_TAG='2.0.3'
MODULE_URL='http://wiki.nginx.org/images/5/51/Nginx-accesskey-2.0.3.tar.gz'
MODULE_PATH="$ROOT/vendor/addons/$MODULE_NAME-$MODULE_TAG"
MODULE_FILE_PATH="$ROOT/vendor/addons/$MODULE_NAME-$MODULE_TAG.tar.gz"

# == INIT

rm -rf "$MODULE_PATH"
mkdir -p "$ADDONS"
echo "[nginx-build]: CD $ADDONS"
cd "$ADDONS"

# == FETCH

if [[ -f "$MODULE_FILE_PATH" ]]; then
  echo "[nginx-build]: EXISTS $MODULE_FILE_PATH"
else
  echo "[nginx-build]: FETCH $MODULE_URL > $MODULE_FILE_PATH"
  ( curl -L -o "$MODULE_FILE_PATH" "$MODULE_URL" && echo "[nginx-build]: OK" ) || (echo "[nginx-build]: FAIL" && exit)
fi

if [[ -s "$MODULE_PATH" ]]; then
  echo "[nginx-build]: EXISTS $MODULE_PATH"
else
  echo "[nginx-build]: EXTRACT $MODULE_FILE_PATH > $MODULE_PATH"
  ( tar -xzvf "$MODULE_FILE_PATH" && echo "[nginx-build]: OK" ) || (echo "[nginx-build]: FAIL" && exit)
  echo "[nginx-build]: REMOVE $MODULE_FILE_PATH"
  rm -f "$MODULE_FILE_PATH"
fi

# == DONE
