#! /usr/bin/env sh
ROOT="$PWD"
VENDOR="$ROOT/vendor"

NGINX_TITLE='Nginx/OpenResty'
NGINX_NAME='ngx_openresty'
NGINX_TAG='v1.2.1.7'
NGINX_URL='git://github.com/agentzh/ngx_openresty.git'
NGINX_PATH="$VENDOR/$NGINX_NAME-$NGINX_TAG"

# == INIT

# rm -rf "$NGINX_PATH"
mkdir -p "$VENDOR"
echo "[nginx-build]: CD $VENDOR"
cd "$VENDOR"

# == FETCH

if [[ -s "$NGINX_PATH" ]]; then
  echo "[nginx-build]: EXISTS $NGINX_PATH"
else
  echo "[nginx-build]: CHECKOUT $NGINX_URL ($NGINX_TAG) > $NGINX_PATH"
  ( git clone --branch "$NGINX_TAG" "$NGINX_URL" "$NGINX_PATH" && echo "[nginx-build]: OK" ) || ( echo "[nginx-build]: FAIL" && exit )
fi

# == SETUP 1/2

echo "[nginx-build]: CD $NGINX_PATH"
cd "$NGINX_PATH"

echo "[nginx-build]: MAKE CLEAN"
make clean

echo "[nginx-build]: MAKE"
( make -j4 && echo "[nginx-build]: OK" ) || (echo "[nginx-build]: FAIL" && exit)

# == SETUP 2/2

NGINX_VERSION=`echo "$NGINX_TAG" | tr -ds 'v' ''`

echo "[nginx-build]: CD $NGINX_PATH/$NGINX_NAME-$NGINX_VERSION"
cd "$NGINX_PATH/$NGINX_NAME-$NGINX_VERSION"

echo "[nginx-build]: MAKE CLEAN"
make clean

echo "[nginx-build]: CONFIGURE"
./configure \
  --without-http_fastcgi_module \
  --without-http_ssi_module \
  --without-http_uwsgi_module \
  --without-mail_pop3_module \
  --without-mail_imap_module \
  --without-mail_smtp_module \
  \
  --with-http_addition_module \
  --with-google_perftools_module \
  --with-http_gzip_static_module \
  --with-http_image_filter_module \
  --with-http_random_index_module \
  --with-http_realip_module \
  --with-http_secure_link_module \
  --with-http_ssl_module \
  --with-http_stub_status_module \
  --with-http_sub_module \
  --with-ld-opt="-L /usr/local/lib" \
  --with-cc-opt="-I /usr/local/include" \
  --with-pcre-jit

  # == http://wiki.nginx.org/Modules
  #
  #   --without-http
  #   --without-http_access_module
  #   --without-http_auth_basic_module
  #   --without-http_autoindex_module
  #   --without-http_browser_module
  #   --without-http_charset_module
  #   --without-http_empty_gif_module
  #   --without-http_fastcgi_module
  #   --without-http_geo_module
  #   --without-http_gzip_module
  #   --without-http_limit_req_module
  #   --without-http_limit_zone_module
  #   --without-http_limit_conn_module
  #   --without-http_map_module
  #   --without-http_memcached_module
  #   --without-http_proxy_module
  #   --without-http_referer_module
  #   --without-http_rewrite_module
  #   --without-http_scgi_module
  #   --without-http_split_clients_module
  #   --without-http_ssi_module
  #   --without-http_upstream_ip_hash_module
  #   --without-http_userid_module
  #   --without-http_uwsgi_module
  #
  #   --with-http_addition_module
  #   --with-http_degradation_module
  #   --with-http_perl_module
  #   --with-http_flv_module
  #   --with-http_geoip_module
  #   --with-google_perftools_module
  #   --with-http_gzip_static_module
  #   --with-http_image_filter_module
  #   --with-http_mp4_module
  #   --with-http_random_index_module
  #   --with-http_realip_module
  #   --with-http_secure_link_module
  #   --with-http_ssl_module
  #   --with-http_stub_status_module
  #   --with-http_sub_module
  #   --with-http_dav_module
  #   --with-http_xslt_module
  #
  # == http://wiki.nginx.org/3rdPartyModules
  #
  #   ...
  #

echo "[nginx-build]: MAKE"
( make -j$(sysctl -n hw.ncpu) && echo "[nginx-build]: OK" ) || echo "[nginx-build]: FAIL"

# == DONE
