#!/usr/bin/env sh

# Stop and remove all existing Docker containers.
docker stop nginx-shell
docker rm nginx-shell

# Create new container instance based on Docker image "nginx-openresty" and run bash shell for debugging.
docker run -i -t -v /vagrant:/data -entrypoint "/bin/bash" -w "/app" -name redis-shell crosbymichael/redis:latest
