#!/usr/bin/env sh

# Create new container instance based on Docker image "crosbymichael/redis" and run it.
CONTAINER_ID=$(docker run -d -v /vagrant:/data -p 6379:6379 -name redis crosbymichael/redis:latest)

# Show running containers.
docker ps

# Show logs for this container.
docker logs $CONTAINER_ID

# docker kill $CONTAINER_ID
