#!/usr/bin/env sh

# Stop and remove all existing Docker containers.
docker stop nginx-test
docker rm nginx-test

# Create new container instance based on Docker image "nginx-openresty" and try to run nginx in foreground to see error logs.
docker run -v /vagrant:/app -link redis:redis -name nginx-test nginx-openresty -p /app/ -c /app/conf/nginx.conf
