#!/usr/bin/env sh
dir=`dirname "$(readlink -f "$0")"`

# Stop and remove all existing Docker containers.
$dir/docker-clean

# Create new container instance based on Docker image "openresty-nginx" and run nginx.
JOB=$(docker run -d -v /vagrant:/app -p 80:8080 -p 443:4433 openresty-nginx nginx -p /app/ -c /app/conf/nginx.conf)

docker port $JOB 8080 | awk -F: '{ print $2 }'
docker logs $JOB
# docker kill $JOB
