#!/usr/bin/env sh

# Stop and remove all existing Docker containers.
containers=$(docker ps -a -q)

echo "docker stop $containers"
docker stop $containers > /dev/null

echo "docker rm $containers"
docker rm $containers > /dev/null
