#! /usr/bin/env sh
source "./script/local-init"

OPENRESTY_NAME="ngx_openresty"
OPENRESTY_PATH="$VENDOR/$OPENRESTY_NAME"
OPENRESTY_NGINX_NAME="nginx"
OPENRESTY_NGINX_VERSION="1.4.3"
OPENRESTY_NGINX_PATH="$OPENRESTY_PATH/build/$OPENRESTY_NGINX_NAME-$OPENRESTY_NGINX_VERSION"

LABEL="[$OPENRESTY_NAME-stop]"

PID_FILE="$TMP/nginx.pid"
SID_FILE="$TMP/nginx.sid"
DEFAULT_CONFIG_PATH="$CONFIG"
CONFIG_PATH="$TMP/conf"
CONFIG_FILE="$CONFIG_PATH/nginx.conf"

touch $SID_FILE

SID=$(cat $SID_FILE)

echo "SID: $SID"

echo "$LABEL: ROOT $ROOT"

# REVIEW: nginx -s stop

if [[ -d "$OPENRESTY_NGINX_PATH/objs" ]]; then
  # nginx: local/sandboxed
  BIN="$OPENRESTY_NGINX_PATH/objs/nginx"
else
  # nginx: global/shared
  BIN="nginx"
fi

echo "$LABEL: USING BIN $BIN"

echo "$LABEL: INFO Stopping Nginx in: $ROOT"
( [[ -s $PID_FILE ]] && ($BIN -s quit -p `pwd`/ -c $CONFIG_FILE) && echo '[nginx-start]: OK' ) || echo "[nginx-start]: SKIP"

rm -rf $CONFIG_PATH
rm $SID_FILE