#! /usr/bin/env sh
ROOT="$PWD"
CONFIG="$PWD/config"
VENDOR="$PWD/vendor"
TMP="$PWD/tmp"
LOG="$PWD/logs"

PID_FILE="$TMP/nginx.pid"
SID_FILE="$TMP/nginx.sid"
DEFAULT_CONFIG_PATH="$PWD/config"
CONFIG_PATH="$TMP/config"
CONFIG_FILE="$CONFIG_PATH/nginx.conf"

if [[ $1 == 'openresty' ]]; then
  NGINX_NAME='ngx_openresty'
  NGINX_TAG='v1.2.1.7'
  NGINX_PATH="$VENDOR/ngx_openresty-v1.2.1.7/ngx_openresty-1.2.1.7/build/nginx-1.2.1"
  echo "openresty-local" > $SID_FILE
else
  NGINX_NAME='nginx'
  NGINX_TAG='stable-1.2'
  NGINX_PATH="$VENDOR/nginx-stable-1.2"
  echo "nginx-local" > $SID_FILE
fi

mkdir -p $LOG
mkdir -p $TMP

echo "[nginx-start]: ROOT $ROOT"

if [[ -d "$NGINX_PATH/objs" ]]; then
  # nginx: local/sandboxed
  BIN="$NGINX_PATH/objs/nginx"
else
  # nginx: global/shared
  BIN="nginx \
        --uwsgi_temp_path $TMP/uwsgi_temp \
        --fastcgi_temp_path $TMP/fastcgi_temp \
        --scgi_temp_path $TMP/scgi_temp \
        --proxy_temp_path $TMP/proxy_temp \
        --client_body_temp_path $TMP/client_body_temp"
fi

echo "[nginx-start]: BIN $BIN"

echo "[nginx-stop]: GENERATE $DEFAULT_CONFIG_PATH > $CONFIG_PATH"
rm -rf $CONFIG_PATH
cp -r $DEFAULT_CONFIG_PATH $CONFIG_PATH

if [ -z $PORT ]; then
  echo "[nginx-start]: PORT -"
else
  echo "[nginx-start]: PORT $PORT"
  sed -i '' -e 's/daemon on/daemon off/g' "$CONFIG_PATH/nginx.conf"
  sed -i '' -e "s/listen [0-9]+ default;/listen $(echo $PORT || echo '8080') default;/g" $CONFIG_PATH/sites/default.conf
fi

if [[ -s $PID_FILE ]]; then
  echo "[nginx-start]: INFO Stopping Nginx in: $ROOT"
  ( $BIN -s quit -p `pwd`/ -c $CONFIG_FILE ) && echo "[nginx-start]: RESTART"
fi

echo "[nginx-start]: INFO Starting Nginx in: $ROOT"
( $BIN -p `pwd`/ -c $CONFIG_FILE && echo '[nginx-start]: OK' ) || echo "[nginx-start]: FAIL"

# NOTE: If Nginx config 'daemon off;' is set no PID is written out becuase of the blocking call - not sure how to do that in a simple way.

if [[ -f $PID_FILE ]]; then
  echo "[nginx-start]: PID $(cat $PID_FILE)"
else
  echo "[nginx-start]: PID -"
fi
