#! /usr/bin/env sh

VERSION='1.3.3'
NAME="nginx-$VERSION"
ROOT="$PWD"

mkdir -p "$ROOT/logs"
mkdir -p "$ROOT/tmp"

echo "[nginx-start]: ROOT $ROOT"

if [[ -d "$ROOT/vendor/$NAME/objs" ]]; then
  echo "[nginx-start]: BIN $ROOT/vendor/$NAME/objs/nginx"
  BIN="$ROOT/vendor/$NAME/objs/nginx"
else
  echo "[nginx-start]: BIN nginx"
  BIN="nginx"
fi

echo "[nginx-start]: INFO Stopping Nginx in: $ROOT"
([[ -s "$ROOT/tmp/nginx.pid" ]] && nginx -s quit -p `pwd`/ -c config/nginx.conf && echo "[nginx-start]: RESTART")

echo "[nginx-start]: INFO Starting Nginx in: $ROOT"
$BIN -p `pwd`/ -c config/nginx.conf && echo '[nginx-start]: OK'

echo "[nginx-start]: PID $(cat "$ROOT/tmp/nginx.pid")"