#! /usr/bin/env sh
source "./script/init"

cat "./logo.txt"

rm -rf "$LOG/*"
rm -rf "$TMP/*"

if [[ "$HTTP_PORT" == "" ]]; then
  HTTP_PORT=$PORT
  if [[ "$HTTP_PORT" == "" ]]; then HTTP_PORT=8080; fi
fi
if [[ "$HTTPS_PORT" == "" ]]; then
  HTTPS_PORT=4433
fi

# HTTP_PORT=$(echo $HTTP_PORT || echo $PORT || echo '8080')
HTTPS_PORT=$(echo $HTTPS_PORT || echo '4433')

OPENRESTY_NAME="ngx_openresty"
OPENRESTY_PATH="$VENDOR/$OPENRESTY_NAME"
OPENRESTY_NGINX_NAME="nginx"
OPENRESTY_NGINX_VERSION="1.4.3"
OPENRESTY_NGINX_PATH="$OPENRESTY_PATH/build/$OPENRESTY_NGINX_NAME-$OPENRESTY_NGINX_VERSION"

LABEL="[$OPENRESTY_NAME-stop]"

echo "$LABEL: LOCAL NGINX BIN: $OPENRESTY_NGINX_PATH"

PID_FILE="$TMP/nginx.pid"
SID_FILE="$TMP/nginx.sid"
DEFAULT_CONFIG_PATH="$PWD/config"
CONFIG_PATH="$TMP/config"
CONFIG_FILE="$CONFIG_PATH/nginx.conf"

echo "openresty-local" > $SID_FILE

echo "$LABEL: ROOT $ROOT"

if [[ -d "$OPENRESTY_NGINX_PATH" ]]; then
  # nginx: local/sandboxed
  BIN="$OPENRESTY_NGINX_PATH/objs/nginx"
else
  # nginx: global/shared
  BIN="nginx"
fi

echo "$LABEL: USING BIN $BIN"

echo "$LABEL: GENERATE $DEFAULT_CONFIG_PATH > $CONFIG_PATH"
rm -rf $CONFIG_PATH
cp -r $DEFAULT_CONFIG_PATH $CONFIG_PATH

echo "$LABEL: HTTP PORT $HTTP_PORT"
echo "$LABEL: HTTPS PORT $HTTPS_PORT"
# sed -i '' -e 's/daemon on/daemon off/g' "$CONFIG_PATH/nginx.conf"
sed -i '' -e "s/listen\ *80[0-9]*\ *default/listen $HTTP_PORT default/g" "$CONFIG_PATH/nginx.conf"
sed -i '' -e "s/listen\ *443[0-9]*\ *default/listen $HTTPS_PORT default/g" "$CONFIG_PATH/nginx.conf"
# cat "$CONFIG_PATH/nginx.conf"

if [[ -s $PID_FILE ]]; then
  echo "$LABEL: INFO Stopping Nginx in: $ROOT"
  ( $BIN -s quit -p `pwd`/ -c $CONFIG_FILE ) && echo "$LABEL: RESTART"
fi

echo "$LABEL: INFO Starting Nginx in: $ROOT"
ulimit -n $ULIMIT
( $BIN -p `pwd`/ -c $CONFIG_FILE && echo '$LABEL: OK' ) || echo "$LABEL: FAIL"

# NOTE: If Nginx config 'daemon off;' is set no PID is written out becuase of the blocking call - not sure how to do that in a simple way.

if [[ -f $PID_FILE ]]; then
  echo "$LABEL: PID $(cat $PID_FILE)"
else
  echo "$LABEL: PID -"
fi
