#!/usr/bin/env sh

sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"

sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
sudo apt-get -y update
sudo apt-get -y install lxc-docker

sudo docker pull ubuntu
# sudo docker run -i -t ubuntu /bin/bash echo "OK"

# REVIEW:
# http://docs.docker.io/en/latest/examples/nodejs_web_app/#nodejs-web-app
# https://www.scriptrock.com/blog/comparing-containers-generating-dockerfiles-guardrail/

sudo sed -e "s/DEFAULT_FORWARD_POLICY=\"DROP\"/DEFAULT_FORWARD_POLICY=\"ACCEPT\"/g" "/etc/default/ufw"
sudo ufw reload
sudo ufw allow 4243/tcp # default Docker port
