#!/usr/bin/env sh

# Reference: https://github.com/dotcloud/docker/blob/master/Vagrantfile

# Install the VirtualBox guest additions if they aren't already installed.
if [ ! -d /opt/VBoxGuestAdditions-4.3.2/ ]; then
  # Update remote package metadata. 'apt-get update' is idempotent.
  apt-get update -q

  # Kernel Headers and dkms are required to build the vbox guest kernel
  # modules.
  apt-get install -q -y linux-headers-generic-lts-raring dkms

  echo 'Downloading VBox Guest Additions...'
  wget -cq http://dlc.sun.com.edgesuite.net/virtualbox/4.3.2/VBoxGuestAdditions_4.3.2.iso

  mount -o loop,ro /home/vagrant/VBoxGuestAdditions_4.3.2.iso /mnt
  /mnt/VBoxLinuxAdditions.run --nox11
  umount /mnt
fi
